[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.26"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "a114f312e075f65bf30d6d9a1430113f857e543b"

[[constraint]]
  name = "github.com/hashicorp/go-getter"
  revision = "a33f09ce9feed989941a4dfe08b3890a0f8aceb9"
